export const colorData = [
  { name: "Black", value: "#000000" },
  { name: "White", value: "#ffffff" },
  { name: "Grey", value: "#9ca3af" },
  { name: "Bisque", value: "#ffe4c4" },
  { name: "Beige", value: "#f5f5dc" },
  { name: "Red", value: "#ef4444" },
  { name: "Navy", value: "#1e3a8a" },
  { name: "Blue", value: "#2563eb" },
  { name: "Skyblue", value: "#dbeafe" },
  { name: "Green", value: "#14532d" },
  { name: "Purple", value: "#9333ea" },
  { name: "Pink", value: "#fce7f3" },
  { name: "Orange", value: "#fb923c" },
  { name: "Yellow", value: "#facc15" },
  { name: "Chartreuse", value: "#7fff00" },
  { name: "Cyan", value: "#00ffff" },
];
